all: sort_stl sort_test2

sort_stl: sort_stl.cpp
	g++ -O2 sort_stl.cpp -Wall -o sort_stl

sort_test2: sort_test2.cpp
	g++ -O2 sort_test2.cpp -Wall -o sort_test2

clean:
	rm -f sort_stl
	rm -f sort_test2
